import Header from '../../Components/Rasindu/Header';
import '../../Components/Rasindu/css/report.css';
import 'jspdf-autotable';
import jsPDF from 'jspdf';


function FinalReport(){
    
    
    


    return(
    <div>
           <Header />
           <br />
           <br />
        
        <div >
        
           <div >
           <br />
           <br />
            <button style={{color:"#ffffff",padding:"px 20px",fontSize:"20px",background:"rgb(236, 67, 0)",marginLeft:"20px",width:"200px",borderRadius:"10px"}} >Download PDF</button>
            <br></br>
            <br></br>

            <label className='rReportLabel' htmlFor="month">Month: </label>
                <select id="month"  >
                    <option value="">Select Month</option>
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">Octomber</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>

           </div>
           <br></br>
           <br></br>
           
           <div className="container" id='report'>
                <p className='rReportp'>Protons E&E</p>
                <p className='rReportp'>+94 774015896</p>
                <p className='rReportp'>protons@gmail.com</p>

                <h3 className='rh3Report'>Final Report</h3>

                <br></br>
                <br></br>
        
                <table className='rTabaleReport'>
                <thead>
                    <tr className="rtrTable">
                        <th className='rthReport'>Date</th>
                        <th className='rthReport'>Amount</th>
                        <th className='rthReport'>Category</th>
                    </tr>
                </thead>
                <tbody>
                
                
                </tbody>
                <tfoot>
                    <tr className="rtrTable">
                        
                    </tr>
                </tfoot>
                </table>
                <br></br>
                <div className="rfooter">
                <p>Generated by Financial Manager</p>
                </div>
            </div>
        </div>
    </div>
    )
}
export default FinalReport; 